### PR TITLE
Bikupan now returns both English and Swedish

### PR DESCRIPTION
**Pull request by withrocks**
Bikupan now returns both English and Swedish so the output looks like
this:

    Ugnsbakad blomkål med ruccolaolja & bulgursallad
    Baked cauliflower with rocket salad oil and bulgur salad

    ... and so on

Reformats that so it looks like:

    Baked cauliflower with rocket salad oil and bulgur salad \
       (Ugnsbakad blomkål med ruccolaolja & bulgursallad)

### CODE REVIEW

**Comment by talavis** [comment]
Afraid I cant get it to work locally. The parser simply raises your exceptiobn with "Can't find today's menu".

**Comment by talavis** [comment]
No matter what I think I would prefer to keep the result as Swedish-only. I would however support adding English as a potential option, with Swedish menu as fallback when English is not available. I will look into it.

**Comment by withrocks** [comment]
Right! I also got that message today, but it worked yesterday. Think there
might be some other underlying issue today. I'll look into it when I have
time, and change it to Swedish only.

**Comment by withrocks** [comment]
I've found out the issue. It's also failing on
http://scilifelab-lunches.herokuapp.com/uu.

I'll send an updated patch.

**Comment by withrocks** [comment]
I've fixed the issue. The thing was that Bikupan now has several menus in the HTML, so it was only searching in last weeks menu. I've also stripped out the English text. (English is overrated anyways.)

**Pull request merged**
